author = Giuseppe Vittucci and Artur Tarassow
email = giuseppe.vittucci@unimib.it
version = 2.1
date = 2019-07-23
description = Wooldridge's test for serial correlation of residuals in panel model
tags = C23 C52
min-version = 2016d
data-requirement = needs-panel-data
label = Autocorrelation-Wooldridge
menu-attachment = MODELWIN/Tests
gui-main = gui_wooldridge_test_serial
model-requirement = panel
public = wooldridge_test_serial gui_wooldridge_test_serial 
help = wooldridge_test_serial_help.txt
sample-script = wooldridge_test_serial_sample.inp
